site_name: Docs
site_url: https://github.com/xfnty/hydro
site_author: xfnty
site_description: This is a demo site
repo_name: xfnty/hydro
repo_url: https://github.com/xfnty/hydro

copyright: Copyright © 2023 xfnty

theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: default

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xfnty

extra_css:
  - assets/extra.css

plugins:
  - search:
  - glightbox:
      draggable: false
  - open-in-new-tab:

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home:
    - index.md
  - Journal:
    - journal/day-1.md
    - journal/day-2.md
    - journal/day-3.md
